(cl:defpackage sound_play-msg
  (:use )
  (:export
   "<SOUNDREQUESTACTIONFEEDBACK>"
   "SOUNDREQUESTACTIONFEEDBACK"
   "<SOUNDREQUESTACTION>"
   "SOUNDREQUESTACTION"
   "<SOUNDREQUESTACTIONRESULT>"
   "SOUNDREQUESTACTIONRESULT"
   "<SOUNDREQUESTACTIONGOAL>"
   "SOUNDREQUESTACTIONGOAL"
   "<SOUNDREQUESTGOAL>"
   "SOUNDREQUESTGOAL"
   "<SOUNDREQUESTRESULT>"
   "SOUNDREQUESTRESULT"
   "<SOUNDREQUESTFEEDBACK>"
   "SOUNDREQUESTFEEDBACK"
   "<SOUNDREQUEST>"
   "SOUNDREQUEST"
  ))

