// Generated by gencpp from file intraface/Emotions.msg
// DO NOT EDIT!


#ifndef INTRAFACE_MESSAGE_EMOTIONS_H
#define INTRAFACE_MESSAGE_EMOTIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <intraface/Emotion.h>

namespace intraface
{
template <class ContainerAllocator>
struct Emotions_
{
  typedef Emotions_<ContainerAllocator> Type;

  Emotions_()
    : header()
    , emotions()  {
    }
  Emotions_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , emotions(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::intraface::Emotion_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::intraface::Emotion_<ContainerAllocator> >::other >  _emotions_type;
  _emotions_type emotions;




  typedef boost::shared_ptr< ::intraface::Emotions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::intraface::Emotions_<ContainerAllocator> const> ConstPtr;

}; // struct Emotions_

typedef ::intraface::Emotions_<std::allocator<void> > Emotions;

typedef boost::shared_ptr< ::intraface::Emotions > EmotionsPtr;
typedef boost::shared_ptr< ::intraface::Emotions const> EmotionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::intraface::Emotions_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::intraface::Emotions_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace intraface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'intraface': ['/home/gauri/intraface_orig/src/intraface/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::intraface::Emotions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intraface::Emotions_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intraface::Emotions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intraface::Emotions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intraface::Emotions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intraface::Emotions_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::intraface::Emotions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25a449b64ef4f8821018398c98ff573c";
  }

  static const char* value(const ::intraface::Emotions_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25a449b64ef4f882ULL;
  static const uint64_t static_value2 = 0x1018398c98ff573cULL;
};

template<class ContainerAllocator>
struct DataType< ::intraface::Emotions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "intraface/Emotions";
  }

  static const char* value(const ::intraface::Emotions_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::intraface::Emotions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## Contains all the predicted emotions info\n\
Header header\n\
\n\
#array containing all the computed emotions\n\
intraface/Emotion[] emotions\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: intraface/Emotion\n\
## Contains an emotion data info\n\
\n\
#emotions confidence\n\
string tag\n\
\n\
#emotions confidence\n\
float32 confidence\n\
";
  }

  static const char* value(const ::intraface::Emotions_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::intraface::Emotions_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.emotions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Emotions_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::intraface::Emotions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::intraface::Emotions_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "emotions[]" << std::endl;
    for (size_t i = 0; i < v.emotions.size(); ++i)
    {
      s << indent << "  emotions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::intraface::Emotion_<ContainerAllocator> >::stream(s, indent + "    ", v.emotions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTRAFACE_MESSAGE_EMOTIONS_H
