// Generated by gencpp from file intraface/Emotion.msg
// DO NOT EDIT!


#ifndef INTRAFACE_MESSAGE_EMOTION_H
#define INTRAFACE_MESSAGE_EMOTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace intraface
{
template <class ContainerAllocator>
struct Emotion_
{
  typedef Emotion_<ContainerAllocator> Type;

  Emotion_()
    : tag()
    , confidence(0.0)  {
    }
  Emotion_(const ContainerAllocator& _alloc)
    : tag(_alloc)
    , confidence(0.0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _tag_type;
  _tag_type tag;

   typedef float _confidence_type;
  _confidence_type confidence;




  typedef boost::shared_ptr< ::intraface::Emotion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::intraface::Emotion_<ContainerAllocator> const> ConstPtr;

}; // struct Emotion_

typedef ::intraface::Emotion_<std::allocator<void> > Emotion;

typedef boost::shared_ptr< ::intraface::Emotion > EmotionPtr;
typedef boost::shared_ptr< ::intraface::Emotion const> EmotionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::intraface::Emotion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::intraface::Emotion_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace intraface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'intraface': ['/home/gauri/intraface_orig/src/intraface/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::intraface::Emotion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intraface::Emotion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intraface::Emotion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intraface::Emotion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intraface::Emotion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intraface::Emotion_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::intraface::Emotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d43fa116b23bb95f464029ea5c22924";
  }

  static const char* value(const ::intraface::Emotion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d43fa116b23bb95ULL;
  static const uint64_t static_value2 = 0xf464029ea5c22924ULL;
};

template<class ContainerAllocator>
struct DataType< ::intraface::Emotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "intraface/Emotion";
  }

  static const char* value(const ::intraface::Emotion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::intraface::Emotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## Contains an emotion data info\n\
\n\
#emotions confidence\n\
string tag\n\
\n\
#emotions confidence\n\
float32 confidence\n\
";
  }

  static const char* value(const ::intraface::Emotion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::intraface::Emotion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tag);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Emotion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::intraface::Emotion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::intraface::Emotion_<ContainerAllocator>& v)
  {
    s << indent << "tag: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.tag);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTRAFACE_MESSAGE_EMOTION_H
