// Generated by gencpp from file intraface/Landmarks.msg
// DO NOT EDIT!


#ifndef INTRAFACE_MESSAGE_LANDMARKS_H
#define INTRAFACE_MESSAGE_LANDMARKS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace intraface
{
template <class ContainerAllocator>
struct Landmarks_
{
  typedef Landmarks_<ContainerAllocator> Type;

  Landmarks_()
    : x()
    , y()  {
    }
  Landmarks_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)  {
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _x_type;
  _x_type x;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::intraface::Landmarks_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::intraface::Landmarks_<ContainerAllocator> const> ConstPtr;

}; // struct Landmarks_

typedef ::intraface::Landmarks_<std::allocator<void> > Landmarks;

typedef boost::shared_ptr< ::intraface::Landmarks > LandmarksPtr;
typedef boost::shared_ptr< ::intraface::Landmarks const> LandmarksConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::intraface::Landmarks_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::intraface::Landmarks_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace intraface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'intraface': ['/home/gauri/intraface_orig/src/intraface/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::intraface::Landmarks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intraface::Landmarks_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intraface::Landmarks_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intraface::Landmarks_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intraface::Landmarks_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intraface::Landmarks_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::intraface::Landmarks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d02d5b87dd0a8706354704c31a3c30e";
  }

  static const char* value(const ::intraface::Landmarks_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d02d5b87dd0a870ULL;
  static const uint64_t static_value2 = 0x6354704c31a3c30eULL;
};

template<class ContainerAllocator>
struct DataType< ::intraface::Landmarks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "intraface/Landmarks";
  }

  static const char* value(const ::intraface::Landmarks_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::intraface::Landmarks_<ContainerAllocator> >
{
  static const char* value()
  {
    return "## 49 face landmarks\n\
\n\
# array wiht all the face landmarks x coordinates\n\
int32[] x\n\
\n\
# array wiht all the face landmarks y coordinates\n\
int32[] y\n\
";
  }

  static const char* value(const ::intraface::Landmarks_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::intraface::Landmarks_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Landmarks_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::intraface::Landmarks_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::intraface::Landmarks_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.y[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTRAFACE_MESSAGE_LANDMARKS_H
